spring:
#  profiles:
#    active: local
  application:
    name: jud-service
  rabbitmq:
    host: ${RABBITMQ_HOST}
    username: ${RABBITMQ_USER}
    virtual_host: ${RABBITMQ_VH}
    password: ${RABBITMQ_PWD}

server:
  port: ${PORT:0}

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}/eureka/
  instance:
    instance-id: ${spring.application.name}:${eureka.application.instance-id:${random.value}}
    hostname: ${RENDER_EXTERNAL_HOSTNAME}
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: 443
    prefer-ip-address: false
    status-page-url: ${RENDER_EXTERNAL_URL}/actuator/info
    health-check-url: ${RENDER_EXTERNAL_URL}/actuator/health